import mongoose, { mongo } from "mongoose";

export const PostSchema = new mongoose.Schema({
    title:{
        type:String,
    },
    tags:[{
        type:String,
        lowercase:true,
    }],
    location:{
        type:String
    },
    place:{
        type:String
    },
    likes:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User'
    }],
    comments:[{
        author:{
            type:mongoose.Schema.Types.ObjectId,
            required:true
        },
        commentedText:{
            type:String
        },
        likes:[{
            type:mongoose.Schema.Types.ObjectId,
            ref:"User"
        }],
        createdAt:{
            type:Date
        },
        nestedComment:[{
            commentedText:{type:String},
            createdAt:{type:Date},
            likes:[{type:mongoose.Schema.Types.ObjectId}]
        }]
    }]
})